url: http://metricsandco.no
baseurl: /

# Site settings
title: Metrics & Co
email: paola@metricsandco.no
description:  >-
  Metrics and Co is specialised in data analysis for online marketing, based in Bergen, Norway.
  We measure and improve campaigns in social networks. 

# Team names, titles and social links
people:
- name: Paola Martinez Perez
  pic: 1
  position: Lead social media analyst
  social:
    - title: twitter
      url: #
    - title: linkedin
      url: https://www.linkedin.com/in/paola-mart%C3%ADnez/
- name: Jesus Gazol
  pic: 2
  position: Lead data analyst
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/jgazol/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: linkedin
    url: http://github.com/jekyll
  - title: facebook
    url: http://github.com/jekyll
  - title: instagram
    url: http://github.com/jekyll
  - title: github
    url: http://github.com/metrics-co

# Postal address (add as many lines as necessary)
address:
  - line: 139 Fleslandsvegen
  - line: Blomsterdalen, 5258

# Build settings
permalink: pretty