url: http://metricsandco.no
baseurl: /

# Site settings
title: Metrics & Co
email: martinez.perez.paola@gmail.com
description:  >-
  "This is a placeholder for Metrics and Co website. Your market research company in Bergen, Norway."


# Team names, titles and social links
people:
- name: Paola Martinez Perez
  pic: 1
  position: Lead
  social:
    - title: twitter
      url: #
    - title: linkedin
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: linkedin
    url: http://github.com/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 139 Fleslandsvegen
  - line: Blomsterdalen, 5258

# Build settings
permalink: pretty